//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carro()
        {
            this.locacao = new HashSet<locacao>();
        }
    
        public int carro_codigo { get; set; }
        public string carro_marca { get; set; }
        public string carro_modelo { get; set; }
        public string carro_ano { get; set; }
        public string carro_placa { get; set; }
        public int carro_km { get; set; }
        public int status_codigo { get; set; }
        public Nullable<int> tipocarro_codigo { get; set; }
        public string carro_cor { get; set; }
        public string carro_nome { get; set; }
        public Nullable<decimal> carro_valorDiaria { get; set; }
    
        public virtual status status { get; set; }
        public virtual tipocarro tipocarro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<locacao> locacao { get; set; }
    }
}
