//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucao
    {
        public int devolucao_codigo { get; set; }
        public System.DateTime devolucao_dataEfetiva { get; set; }
        public int filial_codigo { get; set; }
        public int devolucao_km { get; set; }
        public Nullable<decimal> devolucao_multa { get; set; }
        public Nullable<int> tipopagamento_codigo { get; set; }
        public int locacao_codigo { get; set; }
        public int status_codigo { get; set; }
        public Nullable<int> devolucao_diferencaDias { get; set; }
    
        public virtual filial filial { get; set; }
        public virtual locacao locacao { get; set; }
        public virtual status status { get; set; }
        public virtual tipopagamento tipopagamento { get; set; }
    }
}
