//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionario()
        {
            this.locacao = new HashSet<locacao>();
        }
    
        public int funcionario_codigo { get; set; }
        public string funcionario_nome { get; set; }
        public string funcionario_cpf { get; set; }
        public System.DateTime funcionario_dataNascimento { get; set; }
        public string funcionario_cnh { get; set; }
        public string funcionario_rg { get; set; }
        public string funcionario_endereco { get; set; }
        public string funcionario_telefoneFixo { get; set; }
        public string funcionario_telefoneCelular { get; set; }
        public int cidade_codigo { get; set; }
    
        public virtual cidade cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<locacao> locacao { get; set; }
    }
}
