//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class locacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public locacao()
        {
            this.devolucao = new HashSet<devolucao>();
        }
    
        public int locacao_codigo { get; set; }
        public System.DateTime locacao_dataLocacao { get; set; }
        public System.DateTime locacao_dataDevolucaoPrevista { get; set; }
        public int locacao_qtdeDias { get; set; }
        public int funcionario_codigo { get; set; }
        public int cliente_codigo { get; set; }
        public int carro_codigo { get; set; }
        public int filial_codigo { get; set; }
        public decimal locacao_totalLocacao { get; set; }
        public int tipopagamento_codigo { get; set; }
        public int status_codigo { get; set; }
    
        public virtual carro carro { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devolucao> devolucao { get; set; }
        public virtual filial filial { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual status status { get; set; }
        public virtual tipopagamento tipopagamento { get; set; }
    }
}
