//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_carro
    {
        public int carro_codigo { get; set; }
        public string carro_nome { get; set; }
        public string carro_marca { get; set; }
        public string carro_modelo { get; set; }
        public string carro_ano { get; set; }
        public string carro_placa { get; set; }
        public int carro_km { get; set; }
        public string carro_cor { get; set; }
        public Nullable<decimal> carro_valorDiaria { get; set; }
        public string tipocarro_tipo { get; set; }
        public string status_nome { get; set; }
    }
}
