//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cliente
    {
        public int cliente_codigo { get; set; }
        public string cliente_nome { get; set; }
        public string cliente_cpf { get; set; }
        public System.DateTime cliente_dataNascimento { get; set; }
        public string cliente_cnh { get; set; }
        public string cliente_rg { get; set; }
        public string cliente_endereco { get; set; }
        public string cliente_telefoneFixo { get; set; }
        public string cliente_telefoneCelular { get; set; }
        public string cidade_nome { get; set; }
    }
}
