//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_devolucoes
    {
        public int devolucao_codigo { get; set; }
        public System.DateTime devolucao_dataEfetiva { get; set; }
        public int locacao_codigo { get; set; }
        public System.DateTime locacao_dataDevolucaoPrevista { get; set; }
        public int cliente_codigo { get; set; }
        public string cliente_nome { get; set; }
        public int carro_codigo { get; set; }
        public string carro_nome { get; set; }
        public int devolucao_km { get; set; }
        public Nullable<decimal> devolucao_multa { get; set; }
        public Nullable<int> devolucao_diferencaDias { get; set; }
        public int status_codigo { get; set; }
    }
}
