//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_funcionario
    {
        public int funcionario_codigo { get; set; }
        public string funcionario_nome { get; set; }
        public string funcionario_cpf { get; set; }
        public System.DateTime funcionario_dataNascimento { get; set; }
        public string funcionario_cnh { get; set; }
        public string funcionario_rg { get; set; }
        public string funcionario_endereco { get; set; }
        public string funcionario_telefoneFixo { get; set; }
        public string funcionario_telefoneCelular { get; set; }
        public string cidade_nome { get; set; }
    }
}
