//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_locacoes
    {
        public int locacao_codigo { get; set; }
        public System.DateTime locacao_dataLocacao { get; set; }
        public System.DateTime locacao_dataDevolucaoPrevista { get; set; }
        public int locacao_qtdeDias { get; set; }
        public decimal locacao_totalLocacao { get; set; }
        public int status_codigo { get; set; }
        public int funcionario_codigo { get; set; }
        public string funcionario_nome { get; set; }
        public int cliente_codigo { get; set; }
        public string cliente_nome { get; set; }
        public int carro_codigo { get; set; }
        public string carro_nome { get; set; }
    }
}
